config/routes.rb
Rails.application.routes.draw do
  root 'users#show'  
  resources :contests

  resources :videos
  
  #devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

  get '/contest/:contest_id/:url', to: 'videos#index'
  get '/contest/:contest_id/:url/new', to: 'videos#new'
  post '/contest/:contest_id/:url/save', to: 'videos#create'
  get '/contest/:contest_id/:url/show/:id', to: 'videos#show'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contest.rb
class Contest
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  
  field :title,   type: String
  field :banner
  field :url,   type: String
  field :date_ini,   type: Date
  field :date_end,   type: Date
  field :award,   type: String

  belongs_to :user
  has_many :videos, dependent: :destroy

  has_mongoid_attached_file :banner, styles: { medium_nr: "250x150!" }

  validates_attachment_content_type :banner, content_type: /\Aimage/

  validates_attachment_presence :banner

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contest, only: [:show, :edit, :update, :destroy]  
  before_action :set_current_user, only: [:create, :index]

  # All published contests
  def index
    @contests = Contest.where(user_id: @user.id)
  end

  def show
  end

  def new
    @contest = Contest.new
  end

  def edit
  end

  def create
    @contest = Contest.new(contest_params)

    @contest.user_id = @user.id

    auxurl = @contest.title
    url = auxurl.gsub(/\s+/, "")
    @contest.url = url

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_contest
    @contest = Contest.find(params[:id])
    @videos = @contest.videos.paginate(:page =>params[:page], :per_page => 50)
  end

  def set_current_user
    @user = current_user
  end  

  def contest_params
    params.require(:contest).permit(:title, :banner, :url, :date_ini, :date_end, :award, :user_id)
  end
end

app/views/contests/edit.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Edit contest

      = simple_form_for @contest do |f|
        = f.input :title
        = f.label :url
        %br
        .input-group
          %span.input-group-addon='ec2-52-42-129-57.us-west-2.compute.amazonaws.com:3000/contest/' + @contest.id.to_s + '/'
          = f.input_field :url, class: 'form-control'
        %p
        = f.input :date_ini, as: :date
        = f.input :date_end, as: :date
        = f.input :award, as: :text
        = f.input :banner, as: :file
        %h3
          = f.button :submit, class: 'btn-primary', value: 'Save Contest'
          = link_to "Cancel", :back, class: 'btn btn-danger'

app/views/contests/index.haml
.container
  .row
    - @contests.each do |contest|
      .col-md-3.thumb.contest-thumb{ 'data-contest-id': contest.id }
        = link_to contest, class: 'thumbnail' do
          = image_tag contest.banner.url(:medium_nr), class: 'img-circle'
  .row
    .col-md-12
      .pull-right
        = link_to 'Create new contest', new_contest_url, class: 'btn btn-primary'

app/views/contests/new.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Create new contest

      = simple_form_for @contest, html: { multipart: true } do |f|
        = f.input :title
        = f.input :date_ini, as: :date
        = f.input :date_end, as: :date
        = f.input :award, as: :text
        = f.input :banner, as: :file
        = f.button :submit, class: 'btn-primary', value: 'Create Contest'

app/views/contests/show.haml
.container
  .row.contest-full{ 'data-contest-id': @contest.id }
    .row
      .col-md-6
        %h1= @contest.title
        %p.small
          = link_to 'Back to contest' , contests_path
      .col-md-2
        %h1
          = link_to 'Edit contest', edit_contest_path(@contest), class: 'btn btn-primary'
      .col-md-2
        %h1
          = link_to 'Delete contest', contest_path(@contest), method: :delete, class: 'btn btn-primary'
      .col-md-2
        %h1
          = link_to 'Contest view', '/contest/' + @contest.id.to_s + '/' + @contest.url, class: 'btn btn-primary'
    .row
      .col-md-4
        = image_tag @contest.banner.url, class: 'img-rounded', size: '400x200'
      .col-md-1
      .col-sm-7
        %h4=  'URL: ec2-52-42-129-57.us-west-2.compute.amazonaws.com:3000/' + @contest.id.to_s + '/' + @contest.url
        %h4=  'Initial Date: ' + @contest.date_ini.strftime("%F")
        %h4=  'Final Date: ' + @contest.date_end.strftime("%F")
        %h4=  'Award: ' + @contest.award
    .row
      %h1 Available videos for this contest
    .row
      - @videos.each do |video|
        .col-md-6
          - if video.status=='Generado'
            .col-md-6
              %br
              = image_tag video.thumbnail.url(:medium_nr)
              %br
            .col-md-6{}
              %br
              %b= "Video name: "
              = video.filename
              %br
              %b= "Original file: "
              = video.link_original.original_filename
              %br
              %b= "Converted file: "
              = video.link_converted.original_filename
              %br
              %b= "Size original: "
              = (video.link_original.size/1000000.0).round(2).to_s + " MB"
              %br
              %b= "Size converted: "
              = (video.link_converted.size/1000000.0).round(2).to_s + " MB"
              %br
              %b= "Status: "
              = video.status
          - else
            .col-md-6
              %br
              = image_tag("nofotos.png", size:"250x150")
              %br
            .col-md-6
              %br
              %br
              %b= "Video name: "
              = video.filename
              %br
              %b= "Original file: "
              = video.link_original.original_filename
              %br
              %b= "Size: "
              = (video.link_original.size/1000000.0).round(2).to_s + " MB"
              %br
              %b= "Status: "
              = video.status
    .row
      %br
      = will_paginate @videos, class: 'apple_pagination'