config/routes.rb
Rails.application.routes.draw do
  root 'users#show'  
  resources :contests

  resources :videos
  
  #devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

  get '/contest/:contest_id/:url', to: 'videos#index'
  get '/contest/:contest_id/:url/new', to: 'videos#new'
  post '/contest/:contest_id/:url/save', to: 'videos#create'
  get '/contest/:contest_id/:url/show/:id', to: 'videos#show'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title SmartTools
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    '//vjs.zencdn.net/5.0.2/video-js.css'
    = javascript_include_tag '//vjs.zencdn.net/5.8/video.min.js'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//cdn.pubnub.com/pubnub-dev.js'
    = csrf_meta_tags
  %body{'data-no-turbolink': true}
    - if current_user
      .navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            = link_to 'SmartTools', root_url, class: 'navbar-brand'
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Browse contests', contests_path
            %li
              = link_to 'Create contest', new_contest_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.email
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Profile', current_user
                %li
                  = link_to 'Edit profile', edit_user_path(current_user)
                %li.divider{:role => "separator"}
                %li
                  = link_to 'Log out', destroy_user_session_path, :method => :delete

    = yield

app/views/layouts/devise.haml
!!!
%html
  %head
    %title SmartTools
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{'data-no-turbolink': true}
    .container
      .row
        .col-md-4.col-md-offset-4
          %h1.text-center SmartTools
          = yield